name: Black Formatter

on:
  push:
    branches:
      - '**'  # This will match all branches
      
  pull_request:
    branches:
      - main
      
permissions:
  contents: write    # Allows reading repository contents
  statuses: write   # Allows writing commit statuses
  
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated from v2 to v3, compatible with Node.js 16

      - name: Set up Python
        uses: actions/setup-python@v4 # Updated from v2 to v4, compatible with Node.js 16
        with:
          python-version: '3.12'  # Changed from v3.8 to 3.12

      - name: Install dependencies
        run: |
          pip install black
          
      - name: Run Black to fix code formatting
        run: |
          black .  # This applies code formatting

      - name: Commit changes (if any)
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Apply Black formatting" || echo "No changes to commit"
          git push
